#!/usr/bin/env python3
"""Regenerate README.md's settings reference from web.py's HELP dict.

The UI's hover text and the README's settings table are the same explanations. Left
as two hand-maintained copies they would drift within a release or two, and the stale
one is always the docs. So HELP in web.py is the single source and this rewrites the
block between the SETTINGS-TABLE markers in README.md.

    python3 tools/gen_settings_doc.py          # rewrite README.md in place
    python3 tools/gen_settings_doc.py --check  # exit 1 if it's out of date (CI-able)
"""
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from web import HELP, SETTINGS  # noqa: E402

BEGIN = "<!-- BEGIN SETTINGS-TABLE (generated by tools/gen_settings_doc.py) -->"
END = "<!-- END SETTINGS-TABLE -->"

GROUPS = [
    ("Targets & pacing", ["TARGET_TB", "TARGET_TRACKS", "EXPLORE_RATIO", "MIN_FREE_GB",
                          "STAGING_MIN_FREE_GB", "CONCURRENCY", "TASTE_REFRESH_MIN",
                          "MEASURE_EVERY_SEC", "SCAN_MAX_PROBES_PER_PASS", "PAUSED"]),
    ("Taste weighting", ["TASTE_HALF_LIFE_DAYS", "WEIGHT_NAVIDROME", "WEIGHT_PLEX",
                         "WEIGHT_YTMUSIC"]),
    ("Favorites (full discography + new releases)",
     ["FAVORITES_ENABLED", "FAVORITE_SYNC_HOURS", "FAVORITE_PRIORITY",
      "FAVORITE_INCLUDE_EP", "FAVORITE_INCLUDE_SINGLES", "FAVORITE_INCLUDE_LIVE",
      "FAVORITE_INCLUDE_COMPILATIONS", "FAVORITE_INCLUDE_REMIX"]),
    ("Lossy → FLAC upgrades",
     ["UPGRADE_ENABLED", "UPGRADE_HOUR", "UPGRADE_MAX_PER_RUN",
      "UPGRADE_RECHECK_DAYS", "UPGRADE_ONLY_WHEN_IDLE"]),
]


def defaults():
    """Read the shipped config.env so documented defaults are the real ones."""
    out = {}
    for line in (Path(__file__).parent.parent / "config.env").read_text().splitlines():
        m = re.match(r"^([A-Z_]+)=(.*)$", line)
        if m:
            out[m.group(1)] = m.group(2).split("#")[0].strip()
    return out


def render():
    d = defaults()
    lines = [BEGIN, ""]
    for title, keys in GROUPS:
        lines.append(f"### {title}\n")
        for k in keys:
            if k not in HELP:
                continue
            short, detail = HELP[k]
            kind, lo, hi = SETTINGS[k]
            dv = d.get(k, "—")
            if kind == "bool":
                dv = {"1": "on", "0": "off"}.get(dv, dv)
                rng = "on / off"
            else:
                rng = f"{lo} – {hi}"
            lines.append(f"#### `{k}`")
            lines.append(f"**{short}** · default `{dv}` · {rng}\n")
            for para in detail.split("\n\n"):
                lines.append(para + "\n")
    lines.append(END)
    return "\n".join(lines)


def main():
    readme = Path(__file__).parent.parent / "README.md"
    text = readme.read_text()
    if BEGIN not in text or END not in text:
        sys.exit(f"markers not found in {readme}")
    new = re.sub(re.escape(BEGIN) + r".*?" + re.escape(END), render(), text,
                 flags=re.S)
    if "--check" in sys.argv:
        if new != text:
            sys.exit("README settings table is out of date; run tools/gen_settings_doc.py")
        print("README settings table is up to date")
        return
    readme.write_text(new)
    print(f"wrote {sum(len(k) for _, k in GROUPS)} settings into {readme.name}")


if __name__ == "__main__":
    main()
